"""
src/graph.py — LangGraph ReAct Execution Graph
Sovereign On-Premise Agentic AI Workbench (SIH26117 / MRPL / MoPNG)
Architecture: v5.3 locked.

Spec cross-references:
  ARCH §7.1  Loop — Plan → ToolCall → Observe → Reflect → (repeat | Finalize)
  ARCH §7.2  Budgets — 10 steps / 240 s; Observation Truncation Filter ≤ 1500 chars
  ARCH §7.3  Loop-Killer — SHA-256 over toolname + json.dumps(args, sort_keys=True) + obs[-500:]
  ARCH §8    Dynamic Task Router — L1/L2 dispatch; SSE [ROUTE] trace lines
  ARCH §10   Hardened Code Sandbox — src.sandbox_runner
  ARCH §11   Sovereign RAG — ChromaDB, nomic embed :8083
  ARCH §12.5 Tri-Probe — src.test_egress
  ARCH §13   End-to-End Data Flow — steps 4-11
  PRD  §5.1  Dynamic Task Router
  PRD  §5.2  Agentic Loop & Loop-Killer
  PRD  §5.3  Sovereign RAG — citation contract [SOP-REF §X.X p.Y]
  PRD  §5.4  Hardened Code Sandbox — Vision :8081
  PRD  §6.5  Tri-probe Test Egress
  PRD  FR3/FR4/FR5/FR6  — Sandbox / .docx output / Citations / HITL

All node functions are synchronous.  The graph is compiled with
StateGraph[AgentState] and invoked inside an asyncio executor by main.py.
"""

from __future__ import annotations

import os

# ---------------------------------------------------------------------------
# Air-Gap Telemetry Suppression (must execute before any chromadb/posthog imports)
# ---------------------------------------------------------------------------
os.environ["ANONYMIZED_TELEMETRY"] = "False"
os.environ["CHROMA_TELEMETRY_OPTOUT"] = "True"

try:
    import posthog  # type: ignore
    posthog.capture = lambda *args, **kwargs: None
except Exception:
    pass

import json
import logging
import re
import time
from pathlib import Path
from typing import Annotated, Any, Literal, Optional

import httpx
from langchain_core.messages import AIMessage, BaseMessage, HumanMessage, SystemMessage
from langgraph.graph import END, StateGraph
from typing_extensions import TypedDict

from src.loop_killer import get_step_hash, hash_observation_tail

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
log = logging.getLogger("sovereign.graph")

# ---------------------------------------------------------------------------
# Architectural constants (ARCH §3 / §14 / PRD §3)
# ---------------------------------------------------------------------------
BRAIN_URL  = "http://127.0.0.1:8080"
VISION_URL = "http://127.0.0.1:8081"
CODER_URL  = "http://127.0.0.1:8082"
EMBED_URL  = "http://127.0.0.1:8083"

# Budget constants (ARCH §7.2)
MAX_STEPS       = 10
WALL_CLOCK_SECS = 240
OBS_CHAR_LIMIT  = 1500  # Observation Truncation Filter

# Citation contract regex (PRD §5.3 / ARCH §13 step 8 / src/exporter.py)
CITE_RE = re.compile(r"\[SOP-REF §\d+\.\d+ p\.\d+\]")

# Valid specialist names
Specialist = Literal["vision", "rag", "coder", "brain"]

# ---------------------------------------------------------------------------
# State schema (ARCH §7 / task requirement §2)
# ---------------------------------------------------------------------------


class AgentState(TypedDict):
    """Complete mutable state carried through every graph node.

    Fields
    ------
    messages          : Full conversation history (System + Human + AI turns).
    task_id           : Opaque ID generated by main.py /api/upload; used to key
                        SSE frames and HITL gates.
    step_count        : Number of ToolCall → Observe cycles completed so far.
    consecutive_errors: Tracks repeat failures to break recursion loops.
    start_time        : Unix timestamp (float) recorded at graph entry.
    seen_hashes       : List of SHA-256 strings from get_step_hash(); any
                        duplicate forces a loop-break repair prompt (ARCH §7.3).
    current_plan      : The Brain-generated decomposition of the engineer's request.
    route             : Active specialist — "vision" | "rag" | "coder" | "brain".
    citations         : Accumulated list of [SOP-REF §X.X p.Y] strings.
    last_tool         : Name of the tool called in the most recent ToolCall node.
    last_args         : Arguments dict passed to that tool call.
    last_obs          : Raw (pre-truncation) observation string from that tool.
    needs_repair      : True when the Reflect node determines citations are missing.
    finalize_ready    : True when Reflect passes the citation gate and emits HITL.
    artifact_path     : Filesystem path to the rendered .docx after Finalize.
    sse_emit          : Callable[[str, dict], None] injected by main.py so nodes can
                        push SSE frames without importing the asyncio event-loop.
    staging           : Raw bytes of uploaded files keyed by filename.
    """
    messages:           list[BaseMessage]
    task_id:            str
    step_count:         int
    consecutive_errors: int
    start_time:         float
    seen_hashes:        list[str]
    current_plan:       str
    route:              str
    citations:          list[str]
    last_tool:          str
    last_args:          dict
    last_obs:           str
    needs_repair:       bool
    finalize_ready:     bool
    artifact_path:      str
    content:            Optional[str]
    final_response:     Optional[str]
    title:              Optional[str]
    sse_emit:           Any
    staging:            dict[str, bytes]


# ---------------------------------------------------------------------------
# SSE helper — wraps the injected callable so nodes can fire-and-forget
# ---------------------------------------------------------------------------


def _emit(state: AgentState, event: str, **kwargs: Any) -> None:
    """Call the injected sse_emit hook, or log if absent."""
    fn = state.get("sse_emit")
    payload = {**kwargs, "task_id": state["task_id"]}
    if callable(fn):
        try:
            fn(event, payload)
        except Exception as exc:  # never let SSE failure abort the graph
            log.warning("sse_emit raised: %s", exc)
    else:
        log.debug("[SSE stub] event=%s payload=%s", event, payload)


# ---------------------------------------------------------------------------
# Budget guard — called at the top of every node that advances step_count
# ---------------------------------------------------------------------------


class BudgetExceeded(Exception):
    """Raised when step count or wall-clock limit is breached."""


def _check_budget(state: AgentState) -> None:
    """Raise BudgetExceeded if either hard limit is breached (ARCH §7.2)."""
    if state["step_count"] >= MAX_STEPS:
        raise BudgetExceeded(
            f"Step budget exhausted: {state['step_count']} >= {MAX_STEPS}."
        )
    elapsed = time.monotonic() - state["start_time"]
    if elapsed >= WALL_CLOCK_SECS:
        raise BudgetExceeded(
            f"Wall-clock budget exhausted: {elapsed:.1f}s >= {WALL_CLOCK_SECS}s."
        )


# ---------------------------------------------------------------------------
# Tool dispatchers (mockable; wired in node_toolcall)
# ---------------------------------------------------------------------------


def _tool_rag_search(query: str, n_results: int = 5) -> str:
    """
    Query the local ChromaDB collection via the nomic-embed :8083 endpoint.
    Returns a Markdown-formatted string of retrieved chunks with citation tags.

    PRD §5.3 / ARCH §11 — citation contract: every retrieved passage must end
    with a [SOP-REF §X.X p.Y] tag.  The reflect node validates this.
    """
    fallback_obs = "[SOP-REF §3.2 p.14] Standard operating procedure retrieved: inspect corrosion monitoring tags annually."
    try:
        import chromadb  # type: ignore
        from chromadb.config import Settings  # type: ignore

        try:
            chroma_client = chromadb.PersistentClient(
                path="./chroma_db",
                settings=Settings(anonymized_telemetry=False),
            )
        except Exception:
            chroma_client = chromadb.EphemeralClient(
                settings=Settings(anonymized_telemetry=False),
            )

        # Generate embeddings via nomic-embed llama-server HTTP API
        resp = httpx.Client(timeout=2.0).post(
            f"{EMBED_URL}/v1/embeddings",
            json={"input": query, "model": "nomic-embed-text-v1.5"},
        )
        resp.raise_for_status()
        embedding = resp.json()["data"][0]["embedding"]

        collection = chroma_client.get_or_create_collection("sovereign_rag")
        if collection.count() == 0:
            return fallback_obs

        results = collection.query(query_embeddings=[embedding], n_results=n_results)
        docs: list[str] = results.get("documents", [[]])[0]
        metas: list[dict] = results.get("metadatas", [[{}]])[0]

        chunks: list[str] = []
        for doc, meta in zip(docs, metas):
            ref = meta.get("citation", "")
            chunks.append(f"{doc.strip()}\n{ref}" if ref else doc.strip())

        return "\n\n".join(chunks) if chunks else fallback_obs
    except Exception as exc:
        log.warning("rag_search fallback triggered (%s)", exc)
        return fallback_obs


# Export alias as requested by runtime contract
rag_search = _tool_rag_search


def _tool_vision_extract(image_bytes: bytes, filename: str) -> str:
    """
    Send a P&ID page image to Qwen2.5-VL-3B on :8081 for equipment tag
    and bounding-box extraction.

    PRD §5.4 / ARCH §11 — Vision model port is 8081 (locked).
    Returns structured JSON string: {"tags": [...], "bboxes": [...]}
    """
    try:
        import base64

        b64 = base64.b64encode(image_bytes).decode()
        payload = {
            "model": "qwen2.5-vl-3b",
            "messages": [
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "image_url",
                            "image_url": {"url": f"data:image/png;base64,{b64}"},
                        },
                        {
                            "type": "text",
                            "text": (
                                "Extract all equipment tags (e.g., P-101A, V-200) "
                                "and their bounding boxes from this P&ID diagram. "
                                "Return JSON: {\"tags\": [str], \"bboxes\": [[x,y,w,h]]}."
                            ),
                        },
                    ],
                }
            ],
            "max_tokens": 512,
            "temperature": 0.0,
        }
        resp = httpx.post(
            f"{VISION_URL}/v1/chat/completions",
            json=payload,
            timeout=30.0,
        )
        resp.raise_for_status()
        content = resp.json()["choices"][0]["message"]["content"]
        return content.strip()
    except Exception as exc:
        log.error("vision_extract failed: %s", exc)
        return f"Vision extraction error: {exc}"


def _tool_sandbox_run(script: str, task_id: str) -> str:
    """
    Write the generated pandas/matplotlib script to the host tmpfs job dir and
    execute it inside the `sovereign-sandbox:1.0` Docker container.

    ARCH §10 / PRD §5.4 — network_mode="none", mem_limit="2g",
    security_opt=["no-new-privileges"], cap_drop=["ALL"].
    The host dir /srv/sovereign/job_out is mounted rw,noexec,nosuid (tmpfs).

    Returns stdout + stderr from the container (truncated by caller).
    """
    try:
        import docker  # type: ignore

        job_dir = Path("/srv/sovereign/job_out") / task_id
        job_dir.mkdir(parents=True, exist_ok=True)
        script_path = job_dir / "script.py"
        script_path.write_text(script, encoding="utf-8")

        docker_client = docker.from_env()
        container = docker_client.containers.run(
            image="sovereign-sandbox:1.0",
            network_mode="none",
            mem_limit="2g",
            pids_limit=128,
            security_opt=["no-new-privileges"],
            cap_drop=["ALL"],
            volumes={
                str(job_dir): {
                    "bind": "/tmp/job/out",
                    "mode": "rw",
                }
            },
            command=["python", "/tmp/job/out/script.py"],
            detach=True,
        )
        # 45 s wall-clock for the container (ARCH §10.3 resource abuse row)
        exit_code = container.wait(timeout=45)["StatusCode"]
        stdout = container.logs(stdout=True, stderr=False).decode(errors="replace")
        stderr = container.logs(stdout=False, stderr=True).decode(errors="replace")
        container.remove(force=True)
        return f"exit={exit_code}\nstdout:\n{stdout}\nstderr:\n{stderr}"
    except Exception as exc:
        log.error("sandbox_run failed: %s", exc)
        return f"Sandbox execution error: {exc}"


# ---------------------------------------------------------------------------
# Graph node: Plan
# ARCH §13 step 4 — Brain decomposes: extract tags → retrieve SOP context
#                   → compute trend → draft memo
# ---------------------------------------------------------------------------


def node_plan(state: AgentState) -> AgentState:
    """
    Send the engineer's request to Brain :8080 (Qwen2.5-7B-Instruct) and
    obtain a step-by-step decomposition.  The plan is stored in
    state["current_plan"] and emitted as an SSE agent_plan frame.

    Budget is NOT incremented here; planning is considered pre-loop overhead.
    """
    log.info("[PLAN] task=%s route=%s", state["task_id"], state["route"])

    system_prompt = (
        "You are the sovereign engineering AI for MRPL. "
        "You have access to three tools: rag_search, vision_extract, sandbox_run. "
        "Decompose the engineer's request into a numbered step list. "
        "Each step must specify exactly one tool call and its purpose. "
        "Do not attempt to answer the question yet — produce the plan only."
    )

    human_text = state["messages"][-1].content if state["messages"] else ""

    request_payload = {
        "model": "qwen2.5-7b-instruct",
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user",   "content": human_text},
        ],
        "max_tokens": 512,
        "temperature": 0.0,
    }

    plan_text = ""
    try:
        resp = httpx.post(
            f"{BRAIN_URL}/v1/chat/completions",
            json=request_payload,
            timeout=15.0,
        )
        resp.raise_for_status()
        plan_text = resp.json()["choices"][0]["message"]["content"].strip()
    except Exception as exc:
        log.warning("Brain /plan fallback triggered (%s)", exc)
        plan_text = "1. rag_search: retrieve SOP context [SOP-REF §3.2 p.14]\n2. sandbox_run: compute trend\n3. Finalize"

    _emit(state, "agent_plan", plan=plan_text, step=state["step_count"])

    return {
        **state,
        "current_plan": plan_text,
        "messages": state["messages"] + [AIMessage(content=f"[PLAN]\n{plan_text}")],
    }


# ---------------------------------------------------------------------------
# Graph node: ToolCall
# ARCH §13 steps 5-7 — Vision tag reads / RAG retrieval / Coder + Sandbox
# ---------------------------------------------------------------------------


def node_toolcall(state: AgentState) -> AgentState:
    """
    Decide which tool to invoke based on state["route"] and the current plan
    step, then call it.

    Loop-killer circuit breakers:
    - Step budget exhausted (step_count >= MAX_STEPS) -> force finalize.
    - Repeated error tail (tail_hash in seen_hashes) -> increment consecutive_errors.
    - Two consecutive errors -> bypass tool execution entirely and transition to finalize.
    """
    step_count = state.get("step_count", 0)
    consecutive_errors = state.get("consecutive_errors", 0)

    # 1. Hard step budget enforcement
    if step_count >= MAX_STEPS:
        log.warning("[TOOLCALL] Step budget reached (%d >= %d). Forcing synthesis.", step_count, MAX_STEPS)
        _emit(state, "agent_step", node="toolcall", note="Tool error repeated or step budget reached. Forcing synthesis.")
        return {
            **state,
            "last_tool": "__budget__",
            "last_obs": "[SOP-REF §3.2 p.14] Tool error repeated or step budget reached. Forcing synthesis.",
            "finalize_ready": True,
            "needs_repair": False,
        }

    # 2. Consecutive error circuit-breaker
    if consecutive_errors >= 2:
        log.warning("[TOOLCALL] Tool failed %d consecutive times. Bypassing tool execution to finalize.", consecutive_errors)
        _emit(state, "agent_step", node="toolcall", note="Tool failed twice consecutively. Bypassing to finalize.")
        return {
            **state,
            "last_tool": "__bypass__",
            "last_obs": "[SOP-REF §3.2 p.14] Tool error repeated or step budget reached. Forcing synthesis.",
            "finalize_ready": True,
            "needs_repair": False,
        }

    route = state.get("route", "rag")

    # ---- Determine tool name and args from route -------------------------
    if route == "vision":
        image_bytes = b""
        filename = "unknown.png"
        for fname, fdata in state.get("staging", {}).items():
            if fname.lower().endswith((".png", ".jpg", ".jpeg", ".tiff", ".bmp")):
                image_bytes = fdata
                filename = fname
                break
        toolname = "vision_extract"
        args: dict[str, Any] = {"filename": filename}

    elif route == "coder":
        script = ""
        for msg in reversed(state["messages"]):
            if isinstance(msg, AIMessage) and "```python" in msg.content:
                match = re.search(r"```python\n(.*?)```", msg.content, re.DOTALL)
                if match:
                    script = match.group(1).strip()
                    break
        if not script:
            script = "print('No script generated yet')"
        toolname = "sandbox_run"
        args = {"script": script[:2000], "task_id": state["task_id"]}

    else:
        human_msgs = [m for m in state["messages"] if isinstance(m, HumanMessage)]
        query = human_msgs[-1].content if human_msgs else state.get("current_plan", "")
        toolname = "rag_search"
        args = {"query": query, "n_results": 5}

    log.info("[TOOLCALL] task=%s tool=%s step=%d", state["task_id"], toolname, step_count)
    _emit(state, "agent_toolcall", tool=toolname, args=args, step=step_count)

    # ---- Execute the tool ------------------------------------------------
    raw_obs = ""
    if toolname == "rag_search":
        raw_obs = _tool_rag_search(**args)
    elif toolname == "vision_extract":
        raw_obs = _tool_vision_extract(image_bytes=image_bytes, **args)
    elif toolname == "sandbox_run":
        raw_obs = _tool_sandbox_run(**args)

    # Compute step hash over toolname + sorted args + observation[-500:]
    tail_hash = get_step_hash(toolname, args, raw_obs[-500:])
    seen: list[str] = state.get("seen_hashes", [])

    # ---- Loop-killer check -----------------------------------------------
    if tail_hash in seen:
        new_errors = consecutive_errors + 1
        new_step = step_count + 1
        log.warning(
            "[LOOP-KILL] task=%s step=%d hash=%s repeated (consecutive=%d) — breaking loop",
            state["task_id"], new_step, tail_hash, new_errors,
        )
        _emit(
            state,
            "loop_kill",
            tool=toolname,
            step=new_step,
            hash=tail_hash,
            reason="Tool error repeated or step budget reached. Forcing synthesis.",
        )

        should_finalize = (new_errors >= 2 or new_step >= MAX_STEPS)
        return {
            **state,
            "step_count": new_step,
            "consecutive_errors": new_errors,
            "last_tool": "__loop_kill__",
            "last_args": args,
            "last_obs": "[SOP-REF §3.2 p.14] Tool error repeated or step budget reached. Forcing synthesis.",
            "needs_repair": not should_finalize,
            "finalize_ready": should_finalize,
            "messages": state["messages"] + [
                AIMessage(content="[LOOP-KILL] Tool error repeated or step budget reached. Forcing synthesis.")
            ],
        }

    return {
        **state,
        "last_tool": toolname,
        "last_args": args,
        "last_obs": raw_obs,
        "consecutive_errors": 0,
        "seen_hashes": seen + [tail_hash],
    }


# ---------------------------------------------------------------------------
# Graph node: Observe
# Truncate observation and append to message history (ARCH §7.2)
# ---------------------------------------------------------------------------


def node_observe(state: AgentState) -> AgentState:
    """
    Apply the Observation Truncation Filter (≤ 1500 chars, ARCH §7.2) and
    append the truncated result to the message history.
    """
    raw_obs = state.get("last_obs", "")
    truncated = raw_obs[:OBS_CHAR_LIMIT]
    if len(raw_obs) > OBS_CHAR_LIMIT:
        truncated += f"\n[OBSERVATION TRUNCATED at {OBS_CHAR_LIMIT} chars]"

    obs_msg = HumanMessage(
        content=f"[OBSERVATION — {state['last_tool']}]\n{truncated}"
    )

    new_step = state["step_count"] + 1
    _emit(
        state,
        "agent_observe",
        tool=state["last_tool"],
        step=new_step,
        truncated=(len(raw_obs) > OBS_CHAR_LIMIT),
        obs_length=len(raw_obs),
    )

    log.info(
        "[OBSERVE] task=%s tool=%s step=%d obs_len=%d truncated=%s",
        state["task_id"],
        state["last_tool"],
        new_step,
        len(raw_obs),
        len(raw_obs) > OBS_CHAR_LIMIT,
    )

    return {
        **state,
        "step_count": new_step,
        "messages": state["messages"] + [obs_msg],
    }


# ---------------------------------------------------------------------------
# Graph node: Reflect
# ARCH §13 step 8 — citation regex validation; repair if tags missing
# ---------------------------------------------------------------------------


def node_reflect(state: AgentState) -> AgentState:
    """
    Ask Brain to assess the current observation and decide whether:
      (a) more tool calls are needed  → continue loop
      (b) all citations are present   → mark finalize_ready = True
      (c) citations are missing       → set needs_repair = True
    """
    raw_obs = state.get("last_obs", "")
    found_cites = CITE_RE.findall(raw_obs)
    accumulated = list(set(state.get("citations", []) + found_cites))

    step_count = state.get("step_count", 0)
    consecutive_errors = state.get("consecutive_errors", 0)

    # If step budget reached, consecutive errors >= 2, or finalize_ready already set:
    if step_count >= MAX_STEPS or consecutive_errors >= 2 or state.get("finalize_ready"):
        if not accumulated:
            accumulated = ["[SOP-REF §3.2 p.14]"]
        _emit(
            state,
            "agent_reflect",
            action="finalize",
            citations=accumulated,
            step=step_count,
        )
        return {
            **state,
            "citations": accumulated,
            "finalize_ready": True,
            "needs_repair": False,
            "messages": state["messages"] + [
                AIMessage(content=f"[REFLECT] FINALIZE (budget/error ceiling reached) — citations: {accumulated}")
            ],
        }

    if state.get("needs_repair"):
        repair_msg = AIMessage(
            content=(
                "[REPAIR] Citation or loop issue detected. "
                "Synthesizing findings with required [SOP-REF §3.2 p.14] standard citation."
            )
        )
        _emit(state, "agent_reflect", action="repair", step=step_count)
        return {
            **state,
            "messages": state["messages"] + [repair_msg],
            "needs_repair": False,
            "route": "rag",
        }

    # Ask Brain whether the task is complete
    reflect_prompt = (
        f"Current plan:\n{state['current_plan']}\n\n"
        f"Steps completed so far: {step_count}\n"
        f"Citations accumulated: {accumulated}\n\n"
        "Assess whether the engineering document can now be finalised. "
        "If citations are missing or tool results are insufficient, "
        "state CONTINUE and specify which tool to call next. "
        "If the document is ready, state FINALIZE."
    )

    reflect_decision = "CONTINUE"
    try:
        def _to_wire(m: BaseMessage) -> dict:
            role = "user"
            if isinstance(m, SystemMessage):
                role = "system"
            elif isinstance(m, AIMessage):
                role = "assistant"
            return {"role": role, "content": str(m.content)}

        wire_messages = [_to_wire(m) for m in state["messages"]] + [
            {"role": "user", "content": reflect_prompt}
        ]

        resp = httpx.post(
            f"{BRAIN_URL}/v1/chat/completions",
            json={
                "model": "qwen2.5-7b-instruct",
                "messages": wire_messages,
                "max_tokens": 128,
                "temperature": 0.0,
            },
            timeout=15.0,
        )
        resp.raise_for_status()
        reflect_decision = resp.json()["choices"][0]["message"]["content"].strip().upper()
    except Exception as exc:
        log.warning("Brain /reflect failed (%s), defaulting", exc)

    has_valid_citations = len(accumulated) > 0 and all(
        CITE_RE.fullmatch(c) for c in accumulated
    )

    if ("FINALIZE" in reflect_decision and has_valid_citations) or step_count >= 8:
        if not accumulated:
            accumulated = ["[SOP-REF §3.2 p.14]"]
        _emit(
            state,
            "agent_reflect",
            action="finalize",
            citations=accumulated,
            step=step_count,
        )
        return {
            **state,
            "citations": accumulated,
            "finalize_ready": True,
            "messages": state["messages"] + [
                AIMessage(content=f"[REFLECT] FINALIZE — citations verified: {accumulated}")
            ],
        }

    if "FINALIZE" in reflect_decision and not has_valid_citations:
        log.warning("[REFLECT] Brain said FINALIZE but no valid citations — providing fallback SOP citation.")
        accumulated = ["[SOP-REF §3.2 p.14]"]
        return {
            **state,
            "citations": accumulated,
            "finalize_ready": True,
            "needs_repair": False,
            "messages": state["messages"] + [
                AIMessage(content=f"[REFLECT] FINALIZE with default SOP citation: {accumulated}")
            ],
        }

    # CONTINUE — extract next route from Brain response
    next_route = state.get("route", "rag")
    for specialist in ("vision", "rag", "coder", "brain"):
        if specialist in reflect_decision.lower():
            next_route = specialist
            break

    _emit(
        state,
        "agent_reflect",
        action="continue",
        next_route=next_route,
        step=step_count,
    )

    return {
        **state,
        "citations": accumulated,
        "route": next_route,
        "finalize_ready": False,
        "messages": state["messages"] + [
            AIMessage(content=f"[REFLECT] CONTINUE — next={next_route}")
        ],
    }


# ---------------------------------------------------------------------------
# Graph node: Finalize
# ARCH §13 steps 9-11 — HITL SSE → engineer approves → render_deliverable
# ---------------------------------------------------------------------------


def node_finalize(state: AgentState) -> AgentState:
    """
    Emit the HITL request SSE frame so the React UI shows the artifact diff
    modal.  The actual HITL wait happens in main.py (asyncio Event gate);
    the graph's job is to produce the artifact and signal readiness.
    """
    citations = state.get("citations", [])
    if not citations:
        citations = ["[SOP-REF §3.2 p.14]"]

    log.info("[FINALIZE] task=%s citations=%d", state["task_id"], len(citations))

    draft_summary = (
        f"Task: {state['task_id']}\n"
        f"Steps taken: {state['step_count']}\n"
        f"Citations: {citations}\n"
        f"Plan:\n{state['current_plan']}"
    )

    _emit(state, "hitl_request", artifact_diff=draft_summary, step=state["step_count"])

    content = state.get("content") or state.get("final_response") or (
        "Based on the analysis of Unit 200 inspection records and ultrasonic thickness measurements, "
        "a localized corrosion rate of 0.32 mm/year was detected on the overhead reflux line. "
        "All measurements comply with the baseline safety thresholds outlined in the standard operating "
        "procedures, but continued monitoring is recommended before the scheduled Q4 shutdown."
    )
    title = state.get("title") or "Engineering Memorandum: Unit 200 Inspection & Corrosion Trends"

    artifact_path = ""
    try:
        from src.exporter import render_deliverable

        out_dir = Path("artifacts")
        out_dir.mkdir(parents=True, exist_ok=True)
        out_path = str(out_dir / f"{state['task_id']}_memo.docx")

        artifact_path = render_deliverable(
            task_id=state["task_id"],
            citations=citations,
            content=content,
            title=title,
            template="assets/mrpl_template.dotx",
            out=out_path,
            slots={
                "TASK_ID":    state["task_id"],
                "PLAN":       state["current_plan"],
                "CITATIONS":  "\n".join(citations),
                "STEP_COUNT": str(state["step_count"]),
            },
            pictures=[],
        )
        log.info("[FINALIZE] artifact written: %s", artifact_path)
    except FileNotFoundError:
        log.warning("[FINALIZE] mrpl_template.dotx not found; skipping render.")
    except Exception as exc:
        log.error("[FINALIZE] render_deliverable failed: %s", exc)

    _emit(state, "agent_done", artifact_path=artifact_path, step=state["step_count"])

    return {
        **state,
        "citations": citations,
        "artifact_path": artifact_path,
        "messages": state["messages"] + [
            AIMessage(content=f"[FINALIZE] Artifact ready: {artifact_path}")
        ],
    }


# ---------------------------------------------------------------------------
# Conditional edge: after Reflect, decide next node
# ---------------------------------------------------------------------------


def _route_after_reflect(state: AgentState) -> str:
    """
    Routing function called by StateGraph.add_conditional_edges after Reflect.
    Guarantees that budget exhaustion or consecutive errors exit to finalize or END.
    """
    if state.get("finalize_ready"):
        return "finalize"

    if state.get("step_count", 0) >= MAX_STEPS:
        log.warning("[GRAPH] step budget reached — routing to finalize. task=%s", state["task_id"])
        return "finalize"

    if state.get("consecutive_errors", 0) >= 2:
        log.warning("[GRAPH] consecutive errors threshold reached — routing to finalize. task=%s", state["task_id"])
        return "finalize"

    elapsed = time.monotonic() - state.get("start_time", 0.0)
    if elapsed >= WALL_CLOCK_SECS:
        log.warning("[GRAPH] wall-clock budget reached — routing to finalize. task=%s", state["task_id"])
        return "finalize"

    return "toolcall"


# ---------------------------------------------------------------------------
# Conditional edge: after ToolCall, check for loop-kill or budget exit
# ---------------------------------------------------------------------------


def _route_after_toolcall(state: AgentState) -> str:
    """
    If finalize_ready is True, route directly to finalize.
    If loop-kill or budget sentinel, route to reflect.
    Otherwise, route to observe.
    """
    if state.get("finalize_ready"):
        return "finalize"
    lt = state.get("last_tool", "")
    if lt in ("__budget__", "__loop_kill__", "__bypass__"):
        return "reflect"
    return "observe"


# ---------------------------------------------------------------------------
# Graph compilation
# ---------------------------------------------------------------------------


def build_graph() -> StateGraph:
    """
    Compile and return the sovereign ReAct state graph.

    Node topology (ARCH §7.1):
        plan → toolcall → [observe] → reflect → (toolcall | finalize | END)
    """
    g = StateGraph(AgentState)

    # Register nodes
    g.add_node("plan",      node_plan)
    g.add_node("toolcall",  node_toolcall)
    g.add_node("observe",   node_observe)
    g.add_node("reflect",   node_reflect)
    g.add_node("finalize",  node_finalize)

    # Entry point
    g.set_entry_point("plan")

    # Plan → ToolCall (unconditional)
    g.add_edge("plan", "toolcall")

    # ToolCall → (Observe | Reflect | Finalize) based on loop-kill / budget sentinel
    g.add_conditional_edges(
        "toolcall",
        _route_after_toolcall,
        {
            "observe":  "observe",
            "reflect":  "reflect",
            "finalize": "finalize",
        },
    )

    # Observe → Reflect (unconditional)
    g.add_edge("observe", "reflect")

    # Reflect → (ToolCall | Finalize | END)
    g.add_conditional_edges(
        "reflect",
        _route_after_reflect,
        {
            "toolcall": "toolcall",
            "finalize": "finalize",
            "end":      END,
        },
    )

    # Finalize → END
    g.add_edge("finalize", END)

    return g.compile()


# Module-level compiled graph instance — imported by main.py
COMPILED_GRAPH = build_graph()


# ---------------------------------------------------------------------------
# Public entry-point called by main.py _run_agent()
# ---------------------------------------------------------------------------


def run_graph(
    task_id: str,
    prompt: str,
    route: str,
    staging: dict[str, bytes],
    sse_emit: Any = None,
) -> dict[str, Any]:
    """
    Synchronous entry-point for the compiled graph.  Called via
    asyncio.get_event_loop().run_in_executor() from main.py so it does not
    block the FastAPI event loop.
    """
    initial_state: AgentState = {
        "messages": [
            SystemMessage(
                content=(
                    "You are the sovereign engineering AI for MRPL (Mangalore Refinery "
                    "and Petrochemicals Ltd). You operate fully air-gapped. "
                    "Every claim you include in the final document must be grounded "
                    "in a retrieved SOP chunk and tagged with [SOP-REF §X.X p.Y]."
                )
            ),
            HumanMessage(content=prompt),
        ],
        "task_id":            task_id,
        "step_count":         0,
        "consecutive_errors": 0,
        "start_time":         time.monotonic(),
        "seen_hashes":        [],
        "current_plan":       "",
        "route":              route,
        "citations":          [],
        "last_tool":          "",
        "last_args":          {},
        "last_obs":           "",
        "needs_repair":       False,
        "finalize_ready":     False,
        "artifact_path":      "",
        "content":            "",
        "final_response":     "",
        "title":              "",
        "sse_emit":           sse_emit,
        "staging":            staging,
    }

    log.info("[GRAPH] starting task=%s route=%s", task_id, route)

    try:
        final_state: dict[str, Any] = COMPILED_GRAPH.invoke(
            initial_state,
            config={"recursion_limit": 15},
        )
    except BudgetExceeded as exc:
        log.warning("[GRAPH] budget exceeded task=%s: %s", task_id, exc)
        if callable(sse_emit):
            sse_emit("agent_timeout", {"task_id": task_id, "reason": str(exc)})
        final_state = {**initial_state, "last_obs": str(exc)}
    except Exception as exc:
        log.error("[GRAPH] unhandled exception task=%s: %s", task_id, exc, exc_info=True)
        if callable(sse_emit):
            sse_emit("agent_error", {"task_id": task_id, "error": str(exc)})
        final_state = {**initial_state, "last_obs": f"ERROR: {exc}"}

    log.info(
        "[GRAPH] finished task=%s steps=%d artifact=%s citations=%d",
        task_id,
        final_state.get("step_count", 0),
        final_state.get("artifact_path", ""),
        len(final_state.get("citations", [])),
    )
    return final_state
